In [1]:
import numpy as np
from scipy.stats import chi2_contingency


# Data dari tabel
data = np.array([[8, 22, 15, 5],
                 [10, 28, 20, 7],
                 [12, 30, 20, 8]])


# Menghitung chi-kuadrat
chi2, p, dof, expected = chi2_contingency(data)


# Menampilkan hasil
print(f"Chi-Square Statistic: {chi2}")
print(f"P-value: {p}")
print(f"Degrees of Freedom: {dof}")
print("Expected Frequencies:")
print(expected)


# Menentukan keputusan
alpha = 0.05
if p < alpha:
    print("Tolak H0: Terdapat hubungan antara kecukupan tidur dan kekuatan gowes.")
else:
    print("Gagal Tolak H0: Tidak terdapat hubungan antara kecukupan tidur dan kekuatan gowes.")

Chi-Square Statistic: 0.1873409923409925
P-value: 0.999872291854867
Degrees of Freedom: 6
Expected Frequencies:
[[ 8.10810811 21.62162162 14.86486486  5.40540541]
 [10.54054054 28.10810811 19.32432432  7.02702703]
 [11.35135135 30.27027027 20.81081081  7.56756757]]
Gagal Tolak H0: Tidak terdapat hubungan antara kecukupan tidur dan kekuatan gowes.


In [2]:
import numpy as np
from scipy import stats


# Data sampel nilai dari 15 mahasiswa
data = [904, 920, 973, 1001, 1002, 1002, 1012, 1016, 1039, 1086, 1140, 1146, 1168, 1233, 1255, 1348]


# Melakukan Uji Kolmogorov-Smirnov
stat, p_value = stats.kstest(data, 'norm', args=(np.mean(data), np.std(data, ddof=1)))


print("Statistik Uji Kolmogorov-Smirnov:", stat)
print("p-value:", p_value)


# Menentukan apakah data berdistribusi normal atau tidak
alpha = 0.05
if p_value > alpha:
    print("Data berdistribusi normal (gagal menolak H0)")
else:
    print("Data tidak berdistribusi normal (menolak H0)")

Statistik Uji Kolmogorov-Smirnov: 0.18805925481308217
p-value: 0.5606487063640894
Data berdistribusi normal (gagal menolak H0)


In [3]:
import numpy as np
from scipy.stats import chi2_contingency

# Data dari tabel
data = np.array([[14, 6, 9],
                 [10, 16, 10],
                 [2, 13, 20]])

# Menghitung chi-kuadrat
chi2, p, dof, expected = chi2_contingency(data)

# Menampilkan hasil
print(f"Chi-Square Statistic: {chi2}")
print(f"P-value: {p}")
print(f"Degrees of Freedom: {dof}")
print("Expected Frequencies:")
print(expected)

# Menentukan keputusan
alpha = 0.05
if p < alpha:
    print("Tolak H0: Terdapat hubungan antara pendapatan dan kualitas bahan makanan yang dikonsumsi.")
else:
    print("Gagal Tolak H0: Tidak terdapat hubungan antara pendapatan dan kualitas bahan makanan yang dikonsumsi.")


Chi-Square Statistic: 18.366532937961512
P-value: 0.001046273329595159
Degrees of Freedom: 4
Expected Frequencies:
[[ 7.54 10.15 11.31]
 [ 9.36 12.6  14.04]
 [ 9.1  12.25 13.65]]
Tolak H0: Terdapat hubungan antara pendapatan dan kualitas bahan makanan yang dikonsumsi.


In [2]:
import numpy as np
from scipy import stats

# Data sampel nilai dari 15 mahasiswa
data = [12, 25, 45, 67, 43, 33, 24, 45, 34, 11, 8, 34, 67, 99, 22]

# Sorting data secara ascending
data_sorted = np.sort(data)

# Melakukan Uji Kolmogorov-Smirnov
stat, p_value = stats.kstest(data_sorted, 'norm', args=(np.mean(data_sorted), np.std(data_sorted, ddof=1)))

print("Statistik Uji Kolmogorov-Smirnov:", stat)
print("p-value:", p_value)

# Menentukan apakah data berdistribusi normal atau tidak
alpha = 0.05
if p_value > alpha:
    print("Data berdistribusi normal (gagal menolak H0)")
else:
    print("Data tidak berdistribusi normal (menolak H0)")


Statistik Uji Kolmogorov-Smirnov: 0.18719291305040942
p-value: 0.604384295406073
Data berdistribusi normal (gagal menolak H0)
